---
# pre-commit configs and hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ignore:
# external code in vendor folder
exclude: (vendor)

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
